auth:
  adminUser: admin
  adminPassword: password123

global:
  security:
    allowInsecureImages: true

image:
  repository: keycloak/keycloak
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
ingress:
  enabled: false
  hostname: keycloak.local
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
postgresql:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: latest
  auth:
    postgresPassword: password123
    username: bn_keycloak
    password: password123
    database: bitnami_keycloak
