{{- if .Values.userNamespace.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.userNamespace.serviceAccount.name }}
  namespace: {{ .Values.userNamespace.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver-role
  namespace: {{ .Values.userNamespace.name }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims", "events"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-binding
  namespace: {{ .Values.userNamespace.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.userNamespace.serviceAccount.name }}
  namespace: {{ .Values.userNamespace.name }}
roleRef:
  kind: Role
  name: spark-driver-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
