apiVersion: v1
kind: Secret
metadata:
  name: dremio-mongodb-secrets
  namespace: dremio
type: Opaque
stringData:
  MONGODB_BACKUP_USER: backup
  MONGODB_BACKUP_PASSWORD: backup123
  MONGODB_CLUSTER_ADMIN_USER: clusterAdmin
  MONGODB_CLUSTER_ADMIN_PASSWORD: clusterAdmin123
  MONGODB_CLUSTER_MONITOR_USER: clusterMonitor
  MONGODB_CLUSTER_MONITOR_PASSWORD: clusterMonitor123
  MONGODB_USER_ADMIN_USER: userAdmin
  MONGODB_USER_ADMIN_PASSWORD: userAdmin123
  # Dremio application user
  MONGODB_DATABASE_ADMIN_USER: dremio
  MONGODB_DATABASE_ADMIN_PASSWORD: dremio-mongo-pass
