apiVersion: v2
name: spark-platform
description: Spark Operator and Platform Configurations
type: application
version: 0.1.0
appVersion: "3.5.0"
dependencies:
  - name: spark-operator
    version: "2.4.0"
    repository: "https://kubeflow.github.io/spark-operator"
