#
# Copyright (C) 2017-2019 Dremio Corporation. This file is confidential and private property.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.catalog.serviceAccount }}
  {{- with .Values.catalog.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- include "dremio.imagePullSecrets" $ }}
